# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

jobs:
  Compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew compileJava
      
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ./*
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
        
    - name: Display structure of downloaded files
      run: ls -R
      
  Test:
    needs: Compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ./*
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          
    - name: Display structure of downloaded files
      run: ls -R
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
        
    - uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: ./build/reports # or path/to/artifact
        
  Assemble:
    needs: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ./*
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
        
    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
        
    - uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: ./build/libs/*.jar # or path/to/artifact
        
  Release:
    needs: Assemble
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: buildJar
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: lab4-1.0-SNAPSHOT.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
